import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronRight, Droplets, Instagram, MessageCircle, ShieldCheck, Sparkles, Sprout, UserRound } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

type Stage = "landing" | "quiz" | "processing" | "result";
type Answer = string | string[];

const questions = [
  { id: "caneta", title: "Você está usando ou usou recentemente alguma caneta para emagrecimento?", options: ["Mounjaro (tirzepatida)", "Ozempic (semaglutida)", "Outra caneta para emagrecimento", "Não estou usando atualmente, mas usei recentemente"], icon: Sparkles },
  { id: "tempoCaneta", title: "Há quanto tempo você utiliza ou utilizou a caneta?", options: ["Menos de 3 meses", "Entre 3 e 6 meses", "Entre 6 e 12 meses", "Mais de 1 ano"], icon: Sparkles },
  { id: "inicioQueda", title: "Quando você começou a perceber a queda?", options: ["Antes de começar a caneta", "Pouco tempo depois de começar", "Depois de alguns meses de uso", "Depois de perder bastante peso", "Não consigo relacionar ao início do tratamento"], icon: UserRound },
  { id: "peso", title: "Quanto peso você perdeu desde que começou?", options: ["Até 5 kg", "Entre 5 e 10 kg", "Entre 10 e 20 kg", "Mais de 20 kg", "Não sei informar"], icon: Sprout },
  { id: "tempoPeso", title: "Em quanto tempo aproximadamente você perdeu esse peso?", options: ["Menos de 3 meses", "Entre 3 e 6 meses", "Entre 6 e 12 meses", "Mais de 1 ano", "Ainda estou emagrecendo"], icon: Sprout },
  { id: "cabelo", title: "O que mais chamou sua atenção no cabelo?", options: ["Cai muito cabelo durante o banho ou ao pentear", "Meu cabelo parece estar ficando mais fino", "Percebi redução da densidade no cabelo todo", "Percebi falhas em uma região específica"], icon: UserRound },
  { id: "alimentacao", title: "Você percebeu alguma mudança na alimentação desde que começou a emagrecer?", options: ["Passei a comer bem menos", "Tenho dificuldade para atingir a quantidade de proteínas", "Minha alimentação mudou pouco", "Não percebi mudança significativa", "Não sei avaliar"], icon: Sprout },
  { id: "couro", title: "Você sente algum destes sinais no couro cabeludo?", options: ["Oleosidade excessiva", "Descamação ou coceira", "Dor ou sensibilidade", "Não percebo nenhum desses sinais"], icon: Droplets },
  { id: "regiao", title: "Onde você percebe mais mudanças?", options: ["O cabelo inteiro parece menos denso", "Topo da cabeça", "Entradas ou região frontal", "Falhas em uma região específica", "Não sei identificar"], icon: UserRound },
  { id: "antes", title: "Antes de começar a caneta, você já tinha queda ou afinamento?", options: ["Sim, já tinha", "Não, meu cabelo estava normal", "Já tinha uma queda leve, mas aumentou depois", "Não sei dizer"], icon: ShieldCheck },
  { id: "exames", title: "Você fez exames recentemente?", options: ["Sim", "Não", "Fiz antes de começar o tratamento para emagrecer"], icon: ShieldCheck, multi: true },
  { id: "tratamento", title: "Você já tentou tratar a queda?", options: ["Sim, com shampoos ou tônicos", "Sim, com medicamentos prescritos", "Sim, com suplementação", "Ainda não fiz nenhum tratamento"], icon: Sparkles },
  { id: "familia", title: "Existe histórico de afinamento ou calvície na família?", options: ["Sim", "Não", "Não sei"], icon: ShieldCheck },
] as const;
const examOptions = ["Ferritina", "Vitamina B12", "Vitamina D", "Tireoide", "Zinco", "Nenhum desses exames"];

const Monjaro = () => {
  const [stage, setStage] = useState<Stage>("landing");
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState<Record<string, Answer>>({});
  const leadKey = "tricolofio_monjaro_lead_id";
  const current = questions[step];
  const Icon = current?.icon;

  const start = () => { setAnswers({}); setStep(0); setStage("quiz"); localStorage.removeItem(leadKey); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const createLead = (first: string) => {
    const id = crypto.randomUUID(); localStorage.setItem(leadKey, id); const params = new URLSearchParams(window.location.search);
    void supabase.from("quiz_leads").insert({ id, variante_quiz: "monjaro", status: "iniciado", respostas: { caneta: first }, utm_source: params.get("utm_source"), utm_medium: params.get("utm_medium"), utm_campaign: params.get("utm_campaign"), utm_term: params.get("utm_term"), utm_content: params.get("utm_content"), gclid: params.get("gclid"), landing_page: window.location.href, user_agent: navigator.userAgent }).then(() => undefined);
  };
  const updateLead = (status: "concluido" | "whatsapp_clicado", result: string) => { const id = localStorage.getItem(leadKey); if (!id) return; void supabase.from("quiz_leads").update({ status, resultado: result, respostas: answers, variante_quiz: "monjaro" }).eq("id", id).then(() => undefined); };

  const choose = (answer: string) => {
    if (step === 0) createLead(answer);
    const next = { ...answers, [current.id]: answer }; setAnswers(next);
    if (current.id === "exames" && answer !== "Não") return;
    if (step < questions.length - 1) setStep(step + 1); else setStage("processing");
    window.scrollTo({ top: 0, behavior: "smooth" });
  };
  const toggleExam = (exam: string) => { const selected = Array.isArray(answers.examesSelecionados) ? answers.examesSelecionados : []; setAnswers({ ...answers, examesSelecionados: selected.includes(exam) ? selected.filter((item) => item !== exam) : [...selected, exam] }); };
  const back = () => step > 0 ? setStep(step - 1) : setStage("landing");

  const result = useMemo(() => {
    const falha = answers.cabelo === "Percebi falhas em uma região específica" || answers.regiao === "Falhas em uma região específica";
    const leitura = falha || answers.familia === "Sim" || answers.regiao === "Topo da cabeça" || answers.regiao === "Entradas ou região frontal" || answers.antes === "Sim, já tinha" || answers.inicioQueda === "Não consigo relacionar ao início do tratamento" ? "Padrão que merece investigação específica" : answers.antes === "Já tinha uma queda leve, mas aumentou depois" ? "Queda que aumentou durante o emagrecimento" : answers.antes === "Não, meu cabelo estava normal" && ["Pouco tempo depois de começar", "Depois de alguns meses de uso", "Depois de perder bastante peso"].includes(answers.inicioQueda as string) && (["Entre 10 e 20 kg", "Mais de 20 kg"].includes(answers.peso as string) || ["Menos de 3 meses", "Entre 3 e 6 meses"].includes(answers.tempoPeso as string) || ["Passei a comer bem menos", "Tenho dificuldade para atingir a quantidade de proteínas"].includes(answers.alimentacao as string)) ? "Queda percebida durante o processo de emagrecimento" : "Padrão que merece investigação específica";
    const descriptions: Record<string, string> = {
      "Queda percebida durante o processo de emagrecimento": "Suas respostas indicam que você não apresentava queda relevante antes de iniciar o uso da medicação, e que a percepção da queda surgiu durante ou depois desse processo, associada a uma perda de peso significativa e/ou a mudanças importantes na alimentação. Essa coincidência temporal entre emagrecimento, alimentação e queda capilar merece investigação, não porque a medicação necessariamente tenha causado isso, mas porque perda de peso rápida e mudanças alimentares podem estar relacionadas a alterações no ciclo do fio, por diferentes caminhos. Isso não significa que você deva interromper ou alterar seu tratamento de emagrecimento.",
      "Queda que aumentou durante o emagrecimento": "Suas respostas sugerem que você já percebia queda ou afinamento antes de iniciar a medicação, e notou uma piora durante o processo de emagrecimento. Isso pode indicar que uma alteração capilar que já existia passou por um agravamento nesse período, o que também merece atenção, tanto para entender a causa original quanto os fatores que podem ter contribuído para essa piora.",
      "Padrão que merece investigação específica": "Pelas suas respostas, seu padrão de queda tem características que não se explicam apenas pela relação com o emagrecimento, seja por apresentar falhas em região específica, afinamento concentrado em uma área, histórico familiar relevante, ou por a queda ter começado antes do uso da medicação. Isso não significa que o emagrecimento não tenha nenhuma relação, mas indica que seu caso precisa ser avaliado de forma individual para entender o que realmente está acontecendo com os fios.",
    };
    return { title: leitura, description: `${descriptions[leitura]}\n\nEssa é uma orientação educativa inicial. A avaliação completa com tricoscopia é o que vai esclarecer com precisão o que está acontecendo e o caminho mais adequado para o seu caso. Isso não substitui, em nenhum momento, o acompanhamento do seu médico responsável pelo tratamento de emagrecimento.`, warning: answers.couro === "Dor ou sensibilidade" };
  }, [answers]);
  useEffect(() => { if (stage !== "processing") return; const timer = window.setTimeout(() => { updateLead("concluido", result.title); setStage("result"); }, 1800); return () => window.clearTimeout(timer); }, [stage, result.title]);
  const whatsapp = `https://wa.me/5561982520582?text=${encodeURIComponent(`Olá! Fiz a avaliação educativa sobre queda de cabelo durante o emagrecimento.\n\nResultado: ${result.title}\n\n${result.description}\n\nGostaria de agendar minha consulta.`)}`;

  return <main className="min-h-screen bg-[#fbfaf6] text-[#183c35]">
    <header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6 lg:px-10"><a href="/"><img className="w-[150px] rounded-lg" src="/logo-tricolofio.png" alt="Tricolofio Tricologia" /></a>{stage === "quiz" && <span className="text-xs font-semibold uppercase tracking-[.16em] text-[#67837a]">Avaliação Educativa</span>}</header>
    {stage === "landing" && <section className="hero-shell mx-auto grid min-h-[calc(100vh-90px)] max-w-6xl items-center gap-10 px-5 pb-12 pt-12 lg:grid-cols-[1.05fr_.95fr] lg:px-10"><div className="relative z-[1] max-w-xl animate-rise"><div className="eyebrow"><span className="eyebrow-dot" /> Avaliação educativa</div><h1 className="mt-6 text-[2.7rem] font-medium leading-[1.04] tracking-[-.055em] sm:text-6xl">Sua queda de cabelo pode estar relacionada ao uso da <em>caneta emagrecedora?</em></h1><p className="mt-7 max-w-lg text-lg leading-8 text-[#5b746d]">Faça uma avaliação capilar educativa gratuita, pensada especificamente para quem está em processo de emagrecimento com medicação.</p><button onClick={start} className="primary-button mt-9 w-full sm:w-auto">Fazer minha avaliação educativa <ArrowRight size={19} /></button></div><div className="hero-visual animate-float"><div className="organic-ring" /><div className="photo-card"><img src="/menina-tricologia.png" alt="Profissional de tricologia" /></div></div></section>}
    {stage === "quiz" && <section className="quiz-shell mx-auto flex min-h-screen max-w-3xl flex-col px-5 pb-10 pt-8 lg:px-10"><div className="mb-10 flex items-center gap-4"><button onClick={back} className="icon-button" aria-label="Voltar"><ArrowLeft size={18} /></button><div className="flex-1"><div className="mb-2 flex justify-between text-xs font-bold uppercase tracking-[.13em] text-[#6b8880]"><span>Pergunta {step + 1} de {questions.length}</span><span>{Math.round(((step + 1) / questions.length) * 100)}%</span></div><div className="progress-track"><div className="progress-fill" style={{ width: `${((step + 1) / questions.length) * 100}%` }} /></div></div></div><div key={step} className="animate-rise flex flex-1 flex-col"><div className="question-icon"><Icon size={25} /></div><h2 className="mt-7 max-w-2xl text-3xl font-medium leading-[1.08] tracking-[-.045em] sm:text-5xl">{current.title}</h2><div className="mt-10 grid gap-3">{current.options.map((option, optionIndex) => <button key={option} onClick={() => choose(option)} className="option-button"><span className="option-number">{String(optionIndex + 1).padStart(2, "0")}</span><span>{option}</span><ChevronRight className="ml-auto text-[#99b0a8]" size={19} /></button>)}</div>{current.id === "exames" && answers.exames === "Sim" && <div className="mt-6 rounded-2xl border border-[#dce7df] bg-white p-5"><p className="text-sm font-semibold text-[#31594f]">Quais exames você avaliou?</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{examOptions.map((exam) => <label key={exam} className="flex items-center gap-2 text-sm text-[#5b746d]"><input type="checkbox" checked={Array.isArray(answers.examesSelecionados) && answers.examesSelecionados.includes(exam)} onChange={() => toggleExam(exam)} />{exam}</label>)}</div></div>} {current.id === "exames" && answers.exames !== "Não" && <button onClick={() => setStep(step + 1)} className="primary-button mt-6 w-full">Continuar <ArrowRight size={18} /></button>}<p className="mt-auto pt-12 text-center text-xs text-[#91a59f]">Suas respostas são usadas somente para montar sua orientação inicial.</p></div></section>}
    {stage === "processing" && <section className="flex min-h-screen items-center justify-center px-5"><div className="max-w-md text-center animate-rise"><div className="loader-orbit mx-auto"><div className="loader-core"><Sparkles size={25} /></div></div><h2 className="mt-8 text-4xl font-medium">Organizando sua orientação educativa.</h2></div></section>}
    {stage === "result" && <section className="result-shell mx-auto min-h-screen max-w-5xl px-5 pb-16 pt-12 lg:px-10"><div className="animate-rise"><span className="eyebrow"><span className="eyebrow-dot" /> Sua leitura inicial</span><h2 className="mt-5 max-w-2xl text-4xl font-medium leading-[1.07] tracking-[-.05em] sm:text-6xl">Um olhar educativo para o seu momento.</h2><div className="profile-card mt-12"><span className="card-label">Seu perfil sugere</span><h3>{result.title}</h3><p className="whitespace-pre-line">{result.description}</p>{result.warning && <div className="health-warning">Você indicou sentir dor ou sensibilidade no couro cabeludo. Esse sinal pode sugerir um processo inflamatório e merece atenção próxima — é importante ser avaliado em consulta o quanto antes.</div>}</div><div className="cta-card mt-5"><div className="cta-copy"><span className="cta-spark"><MessageCircle size={20} /></span><div><h3>Converse com nossa equipe.</h3><p>A avaliação completa com tricoscopia ajuda a entender seus próximos passos.</p></div></div><a href={whatsapp} target="_blank" rel="noreferrer" onClick={() => updateLead("whatsapp_clicado", result.title)} className="whatsapp-button"><MessageCircle size={21} fill="currentColor" /> Receber no WhatsApp <ArrowRight size={17} /></a></div><button onClick={start} className="restart-link">Refazer avaliação</button></div></section>}
    <footer className="site-footer"><div className="footer-inner"><div className="footer-brand"><img src="/logo-tricolofio.png" alt="Tricolofio Tricologia" /><p>Cuidado especializado para você se sentir bem com o seu cabelo.</p><p className="footer-technical">Edilaine Albuquerque — Biomédica Esteta Tricologista — CRBM 16081</p><a href="https://www.instagram.com/edilaine_albuquerque" target="_blank" rel="noreferrer" className="footer-social"><Instagram size={17} /> @edilaine_albuquerque</a></div><div className="footer-column"><span>Explore</span><a href="/">Início</a><button onClick={start}>Avaliação Educativa</button><a href={whatsapp} target="_blank" rel="noreferrer">Fale conosco</a></div><div className="footer-column"><span>Atendimento</span><p>Quadra QR 2 Módulo 1 Sala 104 - Candangolândia,<br />Brasília - DF, 71725-211</p><a href="tel:+5561982520582">(61) 9 8252-0582</a><a href="mailto:contato@tricolofio.com.br">contato@tricolofio.com.br</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Tricolofio Tricologia.</span><div className="footer-legal-links"><a href="/politica-de-privacidade">Política de Privacidade</a><a href="/termos-de-uso">Termos de Uso</a></div></div></footer>
  </main>;
};
export default Monjaro;
