import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, ChevronRight, Droplets, Instagram, MessageCircle, ShieldCheck, Sparkles, Sprout, UserRound } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

type Stage = "landing" | "quiz" | "processing" | "result";
const questions = [
  { id: "fase", title: "Em que fase do pós-parto você está?", options: ["Até 3 meses após o parto", "Entre 3 e 6 meses", "Entre 6 e 12 meses", "Mais de 1 ano"], icon: Sparkles },
  { id: "inicio", title: "Quando você começou a perceber a queda?", options: ["Até 2 meses após o parto", "Entre 2 e 4 meses", "Após 4 meses", "Não sei dizer"], icon: UserRound },
  { id: "cabelo", title: "O que mais chamou sua atenção no seu cabelo?", options: ["Cai muito cabelo ao lavar ou pentear", "O cabelo perdeu volume", "Meu cabelo está ficando mais fino", "Percebi falhas em uma região específica"], icon: Sprout },
  { id: "regiao", title: "Onde você percebe mais mudança?", options: ["O cabelo inteiro parece menos denso", "Topo da cabeça", "Entradas ou região frontal", "Falhas localizadas", "Não sei identificar"], icon: UserRound },
  { id: "amamentacao", title: "Você está amamentando atualmente?", options: ["Sim, exclusivamente", "Sim, parcialmente", "Não"], icon: Droplets },
  { id: "alimentacao", title: "Como tem sido sua alimentação desde o parto?", options: ["Tenho dificuldade para me alimentar adequadamente", "Consigo me alimentar bem na maior parte dos dias", "Estou fazendo dieta para emagrecer"], icon: Sprout },
  { id: "investigacao", title: "Você já investigou essa queda?", options: ["Sim, fiz exames ou consultei um profissional", "Usei produtos por conta própria", "Ainda não investiguei"], icon: ShieldCheck },
  { id: "antes", title: "Antes da gravidez você já tinha queda ou afinamento capilar?", options: ["Não", "Sim, uma queda leve", "Sim, afinamento progressivo", "Não sei dizer"], icon: ShieldCheck },
] as const;

const PosParto = () => {
  const [stage, setStage] = useState<Stage>("landing"); const [step, setStep] = useState(0); const [answers, setAnswers] = useState<Record<string, string>>({});
  const current = questions[step]; const Icon = current.icon; const leadKey = "tricolofio_posparto_lead_id";
  const start = () => { setAnswers({}); setStep(0); setStage("quiz"); localStorage.removeItem(leadKey); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const saveStart = (answer: string) => { const id = crypto.randomUUID(); localStorage.setItem(leadKey, id); const p = new URLSearchParams(window.location.search); void supabase.from("quiz_leads").insert({ id, variante_quiz: "pos-parto", status: "iniciado", respostas: { fase: answer }, utm_source: p.get("utm_source"), utm_medium: p.get("utm_medium"), utm_campaign: p.get("utm_campaign"), utm_term: p.get("utm_term"), utm_content: p.get("utm_content"), gclid: p.get("gclid"), landing_page: window.location.href, user_agent: navigator.userAgent }); };
  const updateLead = (status: "concluido" | "whatsapp_clicado", resultado: string) => { const id = localStorage.getItem(leadKey); if (!id) return; void supabase.from("quiz_leads").update({ status, resultado, respostas: answers, variante_quiz: "pos-parto" }).eq("id", id); };
  const choose = (answer: string) => { if (step === 0) saveStart(answer); const next = { ...answers, [current.id]: answer }; setAnswers(next); if (step === questions.length - 1) setStage("processing"); else setStep(step + 1); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const result = useMemo(() => {
    const leitura = answers.cabelo === "Percebi falhas em uma região específica" || answers.regiao === "Falhas localizadas" || ["Topo da cabeça", "Entradas ou região frontal"].includes(answers.regiao) || ["Sim, uma queda leve", "Sim, afinamento progressivo"].includes(answers.antes) ? "Investigação individual" : ["Entre 6 e 12 meses", "Mais de 1 ano"].includes(answers.fase) || ["O cabelo perdeu volume", "Meu cabelo está ficando mais fino"].includes(answers.cabelo) ? "Queda persistente" : answers.inicio === "Entre 2 e 4 meses" && answers.cabelo === "Cai muito cabelo ao lavar ou pentear" && answers.antes === "Não" ? "Queda no período do pós-parto" : "Investigação individual";
    const descriptions: Record<string, string> = { "Queda no período do pós-parto": "Pelas suas respostas, a queda começou dentro do período em que muitas mulheres percebem alterações no ciclo natural dos fios após o parto. Isso merece acompanhamento, principalmente quando a quantidade de fios aumenta de forma evidente. Essa leitura é educativa e não substitui uma avaliação capilar. Na consulta com tricoscopia, é possível identificar o padrão da queda e orientar um plano personalizado para o seu momento.", "Queda persistente": "Suas respostas mostram que a queda permanece mesmo após vários meses do parto ou veio acompanhada de perda de volume e afinamento. Quando isso acontece, vale investigar além da cronologia do pós-parto, porque diferentes fatores podem estar envolvidos. A tricoscopia permite avaliar o couro cabeludo, a densidade dos fios e direcionar a investigação de forma individualizada.", "Investigação individual": "Você relatou um padrão que merece uma investigação mais específica, seja pela presença de falhas, pelo afinamento em regiões determinadas ou por já existir uma alteração antes da gestação. Nem toda queda no pós-parto tem a mesma origem, por isso a avaliação presencial é fundamental para entender o comportamento dos folículos e definir a melhor estratégia de tratamento." };
    return { title: leitura, description: descriptions[leitura] };
  }, [answers]);
  useEffect(() => { if (stage !== "processing") return; const t = window.setTimeout(() => { updateLead("concluido", result.title); setStage("result"); }, 1800); return () => window.clearTimeout(t); }, [stage, result.title]);
  const whatsapp = `https://wa.me/5561982520582?text=${encodeURIComponent(`Olá! Fiz a avaliação educativa sobre queda de cabelo no pós-parto.\n\nResumo:\n• Fase: ${answers.fase || "não informado"}\n• Início da queda: ${answers.inicio || "não informado"}\n• O que percebi: ${answers.cabelo || "não informado"}\n• Região: ${answers.regiao || "não informado"}\n• Amamentação: ${answers.amamentacao || "não informado"}\n• Alimentação: ${answers.alimentacao || "não informado"}\n• Investigação prévia: ${answers.investigacao || "não informado"}\n• Antes da gravidez: ${answers.antes || "não informado"}\n\nResultado educativo: ${result.title}\n${result.description}\n\nGostaria de agendar minha consulta.`)}`;
  const back = () => step > 0 ? setStep(step - 1) : setStage("landing");
  return <main className="min-h-screen bg-[#fbfaf6] text-[#183c35]"><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6 lg:px-10"><a href="/"><img className="w-[150px] rounded-lg" src="/logo-tricolofio.png" alt="Tricolofio Tricologia" /></a>{stage === "quiz" && <span className="text-xs font-semibold uppercase tracking-[.16em] text-[#67837a]">Avaliação Educativa</span>}</header>
    {stage === "landing" && <section className="hero-shell mx-auto grid min-h-[calc(100vh-90px)] max-w-6xl items-center gap-10 px-5 pb-12 pt-12 lg:grid-cols-[1.05fr_.95fr] lg:px-10"><div className="relative z-[1] max-w-xl animate-rise"><div className="eyebrow"><span className="eyebrow-dot" /> Avaliação educativa</div><h1 className="mt-6 text-[2.9rem] font-medium leading-[1.04] tracking-[-.055em] sm:text-6xl">Sua queda de cabelo no pós-parto tem <em>explicação — e tem cuidado.</em></h1><p className="mt-7 max-w-lg text-lg leading-8 text-[#5b746d]">Faça uma avaliação capilar educativa gratuita, pensada especificamente para o período pós-parto.</p><button onClick={start} className="primary-button mt-9 w-full sm:w-auto">Fazer minha avaliação educativa <ArrowRight size={19} /></button></div><div className="hero-visual animate-float"><div className="organic-ring" /><div className="photo-card"><img src="/menina-tricologia.png" alt="Profissional de tricologia" /></div></div></section>}
    {stage === "quiz" && <section className="quiz-shell mx-auto flex min-h-screen max-w-3xl flex-col px-5 pb-10 pt-8 lg:px-10"><div className="mb-10 flex items-center gap-4"><button onClick={back} className="icon-button" aria-label="Voltar"><ArrowLeft size={18} /></button><div className="flex-1"><div className="mb-2 flex justify-between text-xs font-bold uppercase tracking-[.13em] text-[#6b8880]"><span>Pergunta {step + 1} de {questions.length}</span><span>{Math.round(((step + 1) / questions.length) * 100)}%</span></div><div className="progress-track"><div className="progress-fill" style={{ width: `${((step + 1) / questions.length) * 100}%` }} /></div></div></div><div key={step} className="animate-rise flex flex-1 flex-col"><div className="question-icon"><Icon size={25} /></div><h2 className="mt-7 max-w-2xl text-3xl font-medium leading-[1.08] tracking-[-.045em] sm:text-5xl">{current.title}</h2><div className="mt-10 grid gap-3">{current.options.map((option, i) => <button key={option} onClick={() => choose(option)} className="option-button"><span className="option-number">{String(i + 1).padStart(2, "0")}</span><span>{option}</span><ChevronRight className="ml-auto text-[#99b0a8]" size={19} /></button>)}</div><p className="mt-auto pt-12 text-center text-xs text-[#91a59f]">Suas respostas são usadas somente para montar sua orientação inicial.</p></div></section>}
    {stage === "processing" && <section className="flex min-h-screen items-center justify-center px-5"><div className="max-w-md text-center animate-rise"><div className="loader-orbit mx-auto"><div className="loader-core"><Sparkles size={25} /></div></div><h2 className="mt-8 text-4xl font-medium">Organizando sua orientação educativa.</h2></div></section>}
    {stage === "result" && <section className="result-shell mx-auto min-h-screen max-w-5xl px-5 pb-16 pt-12 lg:px-10"><div className="animate-rise"><span className="eyebrow"><span className="eyebrow-dot" /> Sua leitura inicial</span><h2 className="mt-5 max-w-2xl text-4xl font-medium leading-[1.07] tracking-[-.05em] sm:text-6xl">Um olhar educativo para o seu momento.</h2><div className="profile-card mt-12"><span className="card-label">Seu perfil sugere</span><h3>{result.title}</h3><p>{result.description}</p></div><div className="cta-card mt-5"><div className="cta-copy"><span className="cta-spark"><MessageCircle size={20} /></span><div><h3>Converse com nossa equipe.</h3><p>A avaliação completa com tricoscopia ajuda a entender seus próximos passos.</p></div></div><a href={whatsapp} target="_blank" rel="noreferrer" onClick={() => updateLead("whatsapp_clicado", result.title)} className="whatsapp-button"><MessageCircle size={21} fill="currentColor" /> Receber no WhatsApp <ArrowRight size={17} /></a></div><button onClick={start} className="restart-link">Refazer avaliação</button></div></section>}
    <footer className="site-footer"><div className="footer-inner"><div className="footer-brand"><img src="/logo-tricolofio.png" alt="Tricolofio Tricologia" /><p>Cuidado especializado para você se sentir bem com o seu cabelo.</p><p className="footer-technical">Edilaine Albuquerque — Biomédica Esteta Tricologista — CRBM 16081</p><a href="https://www.instagram.com/edilaine_albuquerque" target="_blank" rel="noreferrer" className="footer-social"><Instagram size={17} /> @edilaine_albuquerque</a></div><div className="footer-column"><span>Explore</span><a href="/">Início</a><button onClick={start}>Avaliação Educativa</button><a href={whatsapp} target="_blank" rel="noreferrer">Fale conosco</a></div><div className="footer-column"><span>Atendimento</span><p>Quadra QR 2 Módulo 1 Sala 104 - Candangolândia,<br />Brasília - DF, 71725-211</p><a href="tel:+5561982520582">(61) 9 8252-0582</a><a href="mailto:contato@tricolofio.com.br">contato@tricolofio.com.br</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Tricolofio Tricologia.</span><div className="footer-legal-links"><a href="/politica-de-privacidade">Política de Privacidade</a><a href="/termos-de-uso">Termos de Uso</a></div></div></footer></main>;
};
export default PosParto;
