// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pxytsaqqannfkjyriglm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_tfm9baRh1iZOUIkWB5Mm-g_chYVqkOm";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
