// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xekwufsmglwomcvkmgce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_yFwbi9UCX0kSRa5pA81vdg_VukO3yw7";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
